import { NextPage } from "next";
import Head from "next/head";
import LiveCard from "../components/LiveCard";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>purrchase_client</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <LiveCard />
    </>
  );
};

export default Index;
